sonar.projectKey=yassir003_RAHMA_Medical_Cabinet
sonar.organization=yassir003

# Sources
sonar.sources=Client/src,Server/src/main/java
sonar.tests=Client/src,Server/src/test/java
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*Test.java

# Backend coverage (JaCoCo)
sonar.java.binaries=Server/target/classes
sonar.coverage.jacoco.xmlReportPaths=Server/target/site/jacoco/jacoco.xml

# Frontend coverage (Jest/LCOV)
sonar.javascript.lcov.reportPaths=Client/coverage/lcov.info
sonar.typescript.lcov.reportPaths=Client/coverage/lcov.info
