sonar.projectKey=yassir003_RAHMA_Medical_Cabinet
sonar.organization=yassir003

# Sources
sonar.sources=Client/src,Server/src/main/java
sonar.tests=Client/src,Server/src/test/java
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*Test.java
sonar.exclusions=Client/src/**/*.test.ts,Client/src/**/*.test.tsx,Client/src/**/__tests__/**,Client/src/**/*.d.ts,Client/src/types/**
sonar.coverage.exclusions=Client/src/**/*.test.ts,Client/src/**/*.test.tsx,Client/src/**/__tests__/**,Client/src/**/*.d.ts,Client/src/types/**,Server/src/main/java/**/dto/**,Server/src/main/java/**/entity/**,Server/src/main/java/**/enums/**,Server/src/main/java/**/repository/**,Server/src/main/java/**/*Application.java,Server/src/main/java/**/config/**,Server/src/main/java/**/exception/**,Server/src/main/java/**/messaging/dto/**

# Backend coverage (JaCoCo)
sonar.java.binaries=Server/target/classes
sonar.coverage.jacoco.xmlReportPaths=Server/target/site/jacoco/jacoco.xml

# Frontend coverage (Jest/LCOV)
sonar.javascript.lcov.reportPaths=Client/coverage/lcov.info
sonar.typescript.lcov.reportPaths=Client/coverage/lcov.info
